# Exercise: EDA on Penguins

In this notebook exercise, we will conduct simple EDA steps on the popular penguins dataset.

# Step 1 Understand the Features

You can find information about this dataset here: https://www.kaggle.com/datasets/parulpandey/palmer-archipelago-antarctica-penguin-data

**Question: in your own words**:

1. describe each feature
2. mention its type (numeric or categorical)
3. write its name in Arabic

Please use a Markdown cell to write your answer:

INSERT ANSWER HERE : Musaad Fahad Alanazi

Hint: you can attach an image to illustrate what the features are.

<img src="https://github.com/allisonhorst/palmerpenguins/raw/main/man/figures/culmen_depth.png" width="400">

## Load the dataset

The following will load the dataset automatically.

In [5]:
import seaborn as sns

In [6]:
# You don't have to download the dataset
# the following will download it for you
df = sns.load_dataset('penguins')

Dataset source: https://github.com/allisonhorst/palmerpenguins

## Step 2: look at the DataFrame

- Have a look at the columns and their values (`head`, `sample`, `tail`)
- How many rows and columns do you have? (`df.shape`)
- Look at the full technical information (`info`)

In [10]:
# INSERT CODE HERE
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [13]:
df.sample(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
230,Gentoo,Biscoe,40.9,13.7,214.0,4650.0,Female
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
227,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,Male
101,Adelie,Biscoe,41.0,20.0,203.0,4725.0,Male
96,Adelie,Dream,38.1,18.6,190.0,3700.0,Female

In [12]:
df.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [14]:
df.shape

(344, 7)

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

# Step 3

#### Data types conversion
- We shall convert the string types to `category` to preserve memory
- numeric types can be stored in less precision: `float32`

In [16]:
mem_usage_before = df.memory_usage(deep=True)

In [17]:
# convert categotical types
df['species'] = df['species'].astype('category')
# ...?
# ...?

In [ ]:
# convert numerical types
df['bill_depth_mm'] = df['bill_depth_mm'].astype('float32')
# ...?
# ...?
# ...?

Calculate memory saved after type conversion

In [ ]:
# mem_usage_after = ...?

In [ ]:
print('memory saved:', (mem_usage_before - mem_usage_after).sum() // 1024, 'KB')

# Step 4

#### Detect inconsistency in categorical values

The categorical columns should be checked for any inconsistencies. For example. We look for lowercase, uppercase, or inconsistent use of codes (e.g., "M", "F") with non-codes (e.g., "Male", "Female")  in the `sex` column.

- hint: use `.unique()` to check the number of unique values in a column
- you can also use: `.value_counts()` to check the frequency of each value in a column

In [ ]:
# INSERT CODE HERE

# Step 5: Univariate Analysis

- Separate numerical from categorical columns (hint; use `df.select_dtypes()`)
- Look at the statistical information for each:
    - `df_num.describe().T`
    - `df_cat.describe().T`

In [ ]:
# INSERT CODE HERE

Use charts to plot `value_counts()` categorical variables:
1. plot `species` using bar plot
1. plot `island` using pie chart
1. plot `sex` using horizontal bar plot

In [ ]:
# INSERT CODE HERE

Plot numerical variables:

1. Boxplot: `bill_length_mm`
1. Histogram: `bill_depth_mm`
1. Boxplot: `flipper_length_mm`
1. Histogram: `body_mass_g`

In [ ]:
# INSERT CODE HERE

## Step 6: Outlier detection

Use both methods to mark outliers, for at least one numerical column (e.g. `body_mass_g` or `bill_length_mm`):

1. Z-score method
2. IQR method

In [ ]:
# INSERT CODE HERE

## Step 7: Bivariate Analysis

#### Correlation between numerical features

Let's find out if there is any correlation between numerical features.

- Hint: you can use the `df.corr()` to find the correlation matrix.
- Hint: you can use `sns.heatmap()` to plot the correlation matrix
- Hint: you can use `sns.pairplot()` to visualize relationships.

In [ ]:
# INSERT CODE HERE

Question: Write down your observations based on the correlation heatmap.

**Observations:**

INSERT ANSWER HERE

### Feature Engineering

- We might try adding the feature `bill_size` which is the product of `bill_length` and `bill_depth` to see if it has any significance in the model.
- We might also try `bill_ratio` which is the ratio of `bill_length` to `bill_depth` to see if it has any significance in the model.

In [ ]:
# INSERT CODE HERE

Let's look at the correlation to see whether the newly created features are better.

1. Compute the correlation matrix
1. Select the `'body_mass_g'` column, sort it, and plot it using horizontal bar plot

In [ ]:
# INSERT CODE HERE
# This plots the correlation values for a specific column
# which is usually what we are interested in

# corr['body_mass_g'].sort_values().plot.barh()