# Exercise: Linear Regression

**Your task** is to do the following:

1. Load the data
2. Identify the features and their types
3. Identify the target and its type
4. Explore the data
   - What is the number of samples?
   - What is the distribution of the features? (`min`, `max`, `mean`, `median`, `std`, `quantiles`). Hint: use `DataFrame.describe()`
   - What is the distribution of the target?
   - Are there missing values?
5. What is the relationship between the feature and the target? Increasing, decreasing, random, or non-linear (changing: maybe, increasing until X, then decreasing)? Plot the feature vs the target to answer this.
6. Initialize a regression model
7. Train the model (on the train set)
8. Evaluate the model (on the test set)
9. Make predictions on new cases of your choice

You will do these for all three datasets below..

In [3]:
import pandas as pd

### 1. Hours vs Marks Dataset

<a href="../../../datasets/Rounded_Student_Hours_Studied_vs_Marks_Dataset.csv" download>Download Hours vs Marks Dataset</a> [[Source](https://www.kaggle.com/datasets/souradippal/simple-linear-regression-hours-vs-marks-data)].

In [4]:
pd.read_csv("../../../datasets/Rounded_Student_Hours_Studied_vs_Marks_Dataset.csv").head()

   Hours_Studied  Marks
0           4.76  46.27
1           3.00  34.30
2           2.08  33.63
3           4.04  47.81
4           9.49  66.26

### 2. Experience vs Salary Data

<a href="https://raw.githubusercontent.com/ybifoundation/Dataset/main/Salary%20Data.csv" download>Donwload Experience vs Salary Dataset</a>

In [5]:
pd.read_csv("../../../datasets/Salary Data.csv").head()

   Experience Years  Salary
0               1.1   39343
1               1.2   42774
2               1.3   46205
3               1.5   37731
4               2.0   43525

### 3. BMI and Life Expectancy Dataset

<a href="../../../datasets/bmi_and_life_expectancy.csv" download>Download BMI and Life Expectancy Dataset</a>

Optional: the `Country` column can be used to group some countries together to find out some underlying patterns that are not directly visible in the data.

In [6]:
pd.read_csv("../../../datasets/bmi_and_life_expectancy.csv").head()

       Country  Life expectancy       BMI
0  Afghanistan             52.8  20.62058
1      Albania             76.8  26.44657
2      Algeria             75.5  24.59620
3      Andorra             84.6  27.63048
4       Angola             56.7  22.25083