In [22]:
import pandas as pd
import numpy as np

In [24]:
url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv"
baby = pd.read_csv(url, sep=',')

In [25]:
baby.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

In [26]:
baby.drop(columns=['Unnamed: 0', 'Id'])

            Name  Year Gender State  Count
0           Emma  2004      F    AK     62
1        Madison  2004      F    AK     48
2         Hannah  2004      F    AK     46
3          Grace  2004      F    AK     44
4          Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
1016390     Seth  2014      M    WY      5
1016391  Spencer  2014      M    WY      5
1016392     Tyce  2014      M    WY      5
1016393   Victor  2014      M    WY      5
1016394   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

In [27]:
baby.groupby('Year').sum()['Count'].idxmax()

np.int64(2007)

In [28]:
baby["Gender"].value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

In [ ]:
names = baby.groupby("Name")["Count"].sum()

names.sort_values(ascending=False).head()

Name
Jacob       242874
Emma        214852
Michael     214405
Ethan       209277
Isabella    204798
Name: Count, dtype: int64

In [34]:
len(names)

17632

In [39]:
most = names.idxmax()
most

'Jacob'

In [ ]:
lest = names.min()

lestt = (names == lest).sum()

lestt

np.int64(2578)

In [50]:
median = names.median()
median

np.float64(49.0)

In [52]:
std_occurrence = names.std()
std_occurrence

np.float64(11006.06946789057)

In [53]:
names.describe()

count     17632.000000
mean       2008.932169
std       11006.069468
min           5.000000
25%          11.000000
50%          49.000000
75%         337.000000
max      242874.000000
Name: Count, dtype: float64