In [3]:
import pandas as pd
import numpy as np

In [4]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

chip=pd.read_csv(url, sep='\t')

In [5]:
chip.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [6]:
chip.shape[0]

4622

In [7]:
chip.shape[1]

5

In [8]:
chip.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

In [11]:
chip.index

RangeIndex(start=0, stop=4622, step=1)

In [10]:
a = chip.groupby('item_name')
a=a.sum()
a=a.sort_values(['quantity'], ascending=False)
a.head(1)

,order_id,quantity,choice_description,item_price
item_name,,,,
Chicken Bowl,713926,761,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98 $10.98 $11.25 $8.75 $8.49 $11.25 $8.75 ...

In [12]:
a = chip.groupby('item_name')
a=a.sum()
a=a.sort_values(['order_id'], ascending=False)
a.head(1)

,order_id,quantity,choice_description,item_price
item_name,,,,
Chicken Bowl,713926,761,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98 $10.98 $11.25 $8.75 $8.49 $11.25 $8.75 ...

In [14]:
a = chip.groupby('choice_description')
a=a.sum()
a=a.sort_values(['quantity'], ascending=False)
a.head(1)

,order_id,quantity,item_name,item_price
choice_description,,,,
[Diet Coke],123455,159,Canned SodaCanned SodaCanned Soda6 Pack Soft D...,$2.18 $1.09 $1.09 $6.49 $2.18 $1.25 $1.09 $6.4...

In [18]:
total_orders = chip.quantity.sum()
total_orders

np.int64(4972)

In [23]:
chip.item_price.dtype

In [25]:
dollarizer = lambda x: float(x[1:-1])
chip.item_price = chip.item_price.apply(dollarizer)

In [27]:
chip.item_price.dtype

dtype('float64')

In [32]:
revenue = (chip.quantity * chip.item_price).sum()
print('The revenue is '+str(revenue)+' dollars')

The revenue is 39237.02 dollars

In [37]:
order = chip.order_id.value_counts().count()
print(str(order))

1834

In [61]:
print(str(chip.groupby('order_id')['revenue'].sum().mean()))

21.39423118865867

In [63]:
print(str(chip.item_name.value_counts().count()))

50