In [1]:
import pandas as pd
import numpy as np

In [3]:
cars1 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv")
cars2 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv")
print(cars1.head())
print(cars2.head())

    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  18.0          8           307        130    3504          12.0     70
1  15.0          8           350        165    3693          11.5     70
2  18.0          8           318        150    3436          11.0     70
3  16.0          8           304        150    3433          12.0     70
4  17.0          8           302        140    3449          10.5     70

   origin                        car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0       1  chevrolet chevelle malibu         NaN          NaN          NaN
1       1          buick skylark 320         NaN          NaN          NaN
2       1         plymouth satellite         NaN          NaN          NaN
3       1              amc rebel sst         NaN          NaN          NaN
4       1                ford torino         NaN          NaN          NaN

   Unnamed: 12  Unnamed: 13
0          NaN          NaN
1          NaN          NaN
2          NaN          NaN
3          NaN          NaN
4          NaN          NaN
    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  33.0          4            91         53    1795          17.4     76
1  20.0          6           225        100    3651          17.7     76
2  18.0          6           250         78    3574          21.0     76
3  18.5          6           250        110    3645          16.2     76
4  17.5          6           258         95    3193          17.8     76

   origin                 car
0       3         honda civic
1       1      dodge aspen se
2       1   ford granada ghia
3       1  pontiac ventura sj
4       1       amc pacer d/l

In [4]:
cars1 = cars1.loc[: , 'mpg':'car']
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

In [6]:
print(cars1.shape)
print(cars2.shape)

(198, 9)
(200, 9)

In [14]:
cars = pd.concat([cars1, cars2])
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
196,44.0,4,97,52,2130,24.6,82,2,vw pickup
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage
198,28.0,4,120,79,2625,18.6,82,1,ford ranger
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10

In [16]:
owners = np.random.randint(15000, high=73000 , size=cars.shape[0])
owners

array([46712, 61642, 17907, 17748, 54618, 53228, 54565, 55082, 67941,
       43145, 27751, 17271, 21007, 56038, 53689, 61514, 51646, 40073,
       20619, 57435, 30779, 22809, 18680, 57737, 72544, 54049, 49567,
       35631, 22699, 44673, 49628, 62575, 63491, 20763, 46701, 58888,
       31237, 50511, 57907, 63448, 19096, 45019, 48053, 56995, 21065,
       63268, 39366, 66380, 70721, 33031, 37831, 38252, 30094, 65933,
       41757, 42393, 67163, 36750, 31730, 59275, 53275, 58131, 23620,
       22196, 35834, 31403, 37492, 55245, 29043, 25822, 15574, 68677,
       54278, 56205, 53473, 22943, 54309, 60768, 25118, 54099, 33593,
       69477, 55854, 29219, 42352, 41683, 57942, 53545, 16911, 37940,
       72908, 17396, 28449, 72488, 50915, 32394, 54306, 47119, 15687,
       35927, 38017, 61988, 22761, 20139, 50937, 64941, 33197, 71539,
       38490, 19222, 48133, 50683, 21325, 54521, 52351, 21217, 29227,
       31560, 16633, 19043, 20768, 29589, 37130, 40045, 44823, 71259,
       60683, 63687, 34418, 67064, 17715, 39244, 69850, 72991, 18493,
       33110, 18233, 42859, 60663, 24127, 62367, 71675, 15566, 34584,
       50578, 52454, 15062, 50718, 67827, 36079, 57831, 49501, 15917,
       35792, 68970, 22112, 34841, 21013, 31202, 39200, 55441, 29315,
       48156, 68082, 68485, 67082, 67575, 33135, 38772, 16553, 65495,
       43651, 52398, 16308, 63890, 32530, 41809, 56246, 16101, 59831,
       29210, 33307, 29929, 51287, 48428, 46759, 21267, 61585, 26480,
       18857, 17489, 41155, 65471, 15621, 54935, 61416, 58905, 61134,
       72727, 61970, 63153, 46366, 16380, 66183, 39050, 26016, 66585,
       27854, 65228, 28206, 36582, 52571, 61129, 57014, 43797, 52724,
       44911, 36212, 26536, 55099, 31532, 70721, 44699, 25785, 22046,
       34256, 36217, 53851, 51760, 31422, 38828, 17962, 15877, 49178,
       24195, 43610, 41548, 71386, 61593, 20928, 65992, 17378, 65064,
       18880, 71042, 33847, 27931, 21994, 55171, 49241, 41626, 53021,
       53049, 48116, 20881, 41215, 24085, 40730, 24190, 23450, 16937,
       37509, 38385, 49088, 63390, 25999, 40500, 42605, 43249, 68776,
       27901, 32887, 57819, 24559, 70909, 51419, 53728, 53772, 59527,
       39214, 59334, 25464, 48521, 58240, 67474, 69171, 50622, 62888,
       25975, 53419, 49773, 59804, 60172, 40355, 68952, 66838, 63817,
       28580, 55756, 49085, 18042, 63538, 57240, 35330, 54481, 29750,
       46082, 36443, 64225, 42798, 28116, 56823, 21019, 52581, 52984,
       62020, 62686, 29430, 19690, 44879, 72615, 35586, 36642, 43869,
       48621, 65164, 55650, 27422, 67443, 29155, 34982, 66125, 25347,
       39008, 25839, 44327, 52891, 37518, 19721, 24062, 26456, 52799,
       31591, 48481, 58686, 24199, 54239, 70975, 37831, 54163, 50573,
       56346, 22053, 21239, 19343, 34438, 47958, 39131, 67884, 17792,
       59462, 20187, 43370, 36890, 20730, 28842, 43695, 48131, 30231,
       65580, 53840, 62128, 34194, 41451, 43833, 68728, 47370, 44796,
       37151, 31590, 38556, 34988, 58752, 36526, 20600, 62299, 28384,
       34607, 63649, 68626, 66686, 71122, 47653, 66724, 46244, 60940,
       71581, 33635])

In [17]:
cars['owners'] = owners
cars.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,66724
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,46244
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,60940
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,71581
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,33635