In [5]:
import pandas as pd 
import numpy as np
import datetime

In [15]:
url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data"
data = pd.read_csv(url, sep = "\s+")
data.head()

<>:2: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:2: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
/var/folders/v6/4v1dj_sd7s7fs6l6c7wpdcy00000gn/T/ipykernel_21458/3657022000.py:2: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  data = pd.read_csv(url, sep = "\s+")

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,61,1,1,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,61,1,2,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,61,1,3,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,61,1,4,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,61,1,5,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

In [19]:
def fix_year(year):
    year = int(year)
    return 1900 + year if year > 50 else 2000 + year

data["Yr"] = data["Yr"].apply(fix_year)
data.head()

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,5761,1,1,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,5761,1,2,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,5761,1,3,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,5761,1,4,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,5761,1,5,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

In [21]:
data.index = pd.to_datetime(
    {
        "year": data["Yr"],
        "month": data["Mo"],
        "day": data["Dy"]
    }
)

data = data.drop(columns=["Yr", "Mo", "Dy"])
data.head()

KeyError: 'Yr'

In [23]:
data.isnull().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

In [24]:
data.notnull().sum()

RPT    6568
VAL    6571
ROS    6572
KIL    6569
SHA    6572
BIR    6574
DUB    6571
CLA    6572
MUL    6571
CLO    6573
BEL    6574
MAL    6570
dtype: int64

In [25]:
data.sum().sum() / data.notna().sum().sum()

np.float64(10.227883764282181)

In [26]:
data.describe(percentiles=[])

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,6568.000000,6571.000000,6572.000000,6569.000000,6572.000000,6574.000000,6571.000000,6572.000000,6571.000000,6573.000000,6574.000000,6570.000000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000

In [27]:
day_stats = pd.DataFrame()

day_stats['min'] = data.min(axis = 1) 

day_stats['max'] = data.max(axis = 1) 

day_stats['mean'] = data.mean(axis = 1) 

day_stats['std'] = data.std(axis = 1) 

day_stats.head()

             min    max       mean       std
5761-01-01  9.29  18.50  13.018182  2.808875
5761-01-02  6.50  17.54  11.336364  3.188994
5761-01-03  6.17  18.50  11.641818  3.681912
5761-01-04  1.79  11.75   6.619167  3.198126
5761-01-05  6.17  13.33  10.630000  2.445356

In [28]:
data.loc[data.index.month == 1].mean()

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

In [30]:
data.groupby(data.index.to_period('Y')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
5761,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
5762,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
5763,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
5764,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
5765,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
5766,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
5767,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
5768,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
5769,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
5770,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
5771,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
5772,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
5773,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
5774,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
5775,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
5776,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
5777,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
5778,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

In [31]:
data.groupby(data.index.to_period('M')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
5761-01,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226
5761-02,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
5761-03,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
5761-04,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
5761-05,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
...,...,...,...,...,...,...,...,...,...,...,...,...
5778-08,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
5778-09,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
5778-10,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
5778-11,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
5778-12,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

In [32]:
data.groupby(data.index.to_period('W')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
5760-12-29/5761-01-04,14.707500,12.823333,12.020000,7.625000,9.443333,6.647500,11.262500,7.360000,8.737500,8.950000,13.562500,13.115000
5761-01-05/5761-01-11,12.504286,11.032857,10.917143,5.654286,9.540000,6.987143,10.435714,7.731429,8.137143,9.001429,13.421429,14.195714
5761-01-12/5761-01-18,14.964286,9.801429,14.225714,7.131429,7.995000,6.501429,9.464286,7.528571,7.077143,8.810000,10.471429,10.875714
5761-01-19/5761-01-25,13.375714,9.620000,13.448571,6.155714,10.494286,8.858571,9.661429,9.394286,7.381429,8.825714,11.845714,14.327143
5761-01-26/5761-02-01,19.125000,17.588571,15.314286,11.804286,16.664286,12.911429,14.988571,12.332857,13.577143,13.795714,19.294286,19.364286
...,...,...,...,...,...,...,...,...,...,...,...,...
5778-11-30/5778-12-06,19.077143,16.060000,17.427143,8.464286,14.304286,12.577143,15.095714,11.460000,13.060000,13.338571,15.758571,22.164286
5778-12-07/5778-12-13,20.771429,19.804286,16.904286,10.062857,15.118571,12.101429,13.227143,12.317143,13.352857,13.911429,17.725714,20.982857
5778-12-14/5778-12-20,12.674286,9.562857,12.238571,3.797143,7.177143,3.928571,6.400000,4.948571,5.115714,5.262857,8.280000,14.224286
5778-12-21/5778-12-27,11.868571,9.362857,13.855714,4.962857,8.434286,7.342857,9.715714,9.167143,8.512857,8.582857,10.685714,21.501429
5778-12-28/5779-01-03,16.510000,11.800000,19.115000,8.107500,10.665000,9.950000,17.707500,13.302500,13.447500,14.492500,16.855000,30.477500

In [33]:
weekly = data.resample('W').agg(['min','max','mean','std'])

weekly.loc[weekly.index[1:53], "RPT":"MAL"] .head(10)

              RPT                                VAL                    \
              min    max       mean       std    min    max       mean
5761-01-11  10.58  13.50  12.504286  1.225709   8.12  14.29  11.032857
5761-01-18   9.04  19.83  14.964286  4.574403   3.54  14.37   9.801429
5761-01-25   4.92  25.04  13.375714  6.418735   3.42  14.83   9.620000
5761-02-01  12.21  24.37  19.125000  5.207002  11.42  23.91  17.588571
5761-02-08  10.58  24.54  19.172857  5.233500   9.46  24.21  16.952857
5761-02-15   6.04  22.50  16.617143  5.209193  11.54  19.70  14.541429
5761-02-22   7.79  16.79  13.058571  3.209042   8.63  20.17  13.592857
5761-03-01   8.71  25.80  16.002857  6.321805   7.08  21.50  14.530000
5761-03-08   4.88  13.33   9.571429  3.259378   8.08  17.00  11.188571
5761-03-15  10.63  14.79  11.971667  1.487998  10.17  16.96  13.758571

                        ROS         ...        CLO              BEL         \
                 std    min    max  ...       mean       std    min    max
5761-01-11  2.123525   7.62  19.50  ...   9.001429  1.108609   8.12  20.71
5761-01-18  3.863235   7.08  20.79  ...   8.810000  5.506115   5.25  15.92
5761-01-25  3.815993   7.29  25.84  ...   8.825714  4.807289   6.50  23.09
5761-02-01  4.397656   9.04  22.29  ...  13.795714  5.600863   9.17  27.71
5761-02-08  5.437256  10.00  21.34  ...  11.900000  3.801158   9.71  26.38
5761-02-15  3.109279   6.13  19.67  ...  14.005714  2.394889  14.09  28.62
5761-02-22  3.652774   6.08  14.75  ...  12.130000  2.444136  12.12  29.63
5761-03-01  4.522433  11.17  22.42  ...  13.780000  4.249851   9.59  23.21
5761-03-08  3.603204   7.54  13.67  ...   9.930000  3.139591  10.21  23.45
5761-03-15  2.411952   9.04  16.38  ...  12.297143  2.230835  12.29  22.71

                                   MAL
                 mean       std    min    max       mean       std
5761-01-11  13.421429  4.389109  11.83  16.92  14.195714  2.095136
5761-01-18  10.471429  4.321795   5.17  17.96  10.875714  5.086953
5761-01-25  11.845714  6.057378   6.79  25.25  14.327143  6.958874
5761-02-01  19.294286  6.699054   8.00  27.63  19.364286  6.824443
5761-02-08  17.571429  6.028215   7.17  21.84  14.482857  5.520524
5761-02-15  21.040000  5.075155  10.96  21.09  16.734286  4.008927
5761-02-22  18.685714  5.749165   6.67  22.58  15.155714  5.458504
5761-03-01  18.671429  4.706724   9.21  23.87  16.486667  5.449237
5761-03-08  15.677143  4.628393   5.54  16.38  11.808571  4.079050
5761-03-15  19.272857  3.512291  13.50  22.54  17.141429  3.099637

[10 rows x 48 columns]